import PptxGenJS from 'pptxgenjs'
import type { Slide } from '../store'
import { extractCodeBlocks, extractMermaidBlocks } from './markdown'

interface ExportOptions {
  title: string
  author: string
}

// Color scheme
const COLORS = {
  bg: '0f1117',
  bgCard: '161822',
  bgTertiary: '1e2030',
  text: 'e4e6f0',
  textSecondary: '8b8fa8',
  primary: '6c7ae0',
  accent: '00d4aa',
  border: '2a2d3e'
}

/**
 * Export slides to PPTX file
 */
export async function exportToPptx(slides: Slide[], options: ExportOptions) {
  const pptx = new PptxGenJS()

  pptx.author = options.author
  pptx.title = options.title
  pptx.subject = 'Generated by PPT Kit'
  pptx.layout = 'LAYOUT_WIDE'

  for (const slide of slides) {
    const pptSlide = pptx.addSlide()

    // Set background
    pptSlide.background = { color: COLORS.bg }

    // Extract title from markdown
    const titleMatch = slide.markdown.match(/^#\s+(.+)$/m)
    const title = titleMatch ? titleMatch[1].replace(/[*_~`]/g, '').replace(/🚀|📝|🎨|📊|📤|🎯|⚡|🎉/g, '').trim() : slide.title

    switch (slide.layout) {
      case 'title':
        renderTitleSlide(pptSlide, title, slide.markdown)
        break
      case 'code':
        renderCodeSlide(pptSlide, title, slide.markdown)
        break
      default:
        renderContentSlide(pptSlide, title, slide.markdown)
        break
    }
  }

  await pptx.writeFile({ fileName: `${options.title}.pptx` })
}

function renderTitleSlide(slide: PptxGenJS.Slide, title: string, markdown: string) {
  slide.addShape('rect' as any, {
    x: 0.5, y: 2.2, w: 2, h: 0.06,
    fill: { color: COLORS.primary }
  })

  slide.addText(title, {
    x: 0.5, y: 2.4, w: 12, h: 1.2,
    fontSize: 36, fontFace: 'Microsoft YaHei',
    color: COLORS.text, bold: true
  })

  const lines = markdown.split('\n').filter(l => l.trim() && !l.startsWith('#'))
  const subtitle = lines.slice(0, 3).map(l => l.replace(/^[-*]\s+/, '').replace(/[*_~`]/g, '')).join('\n')

  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.5, y: 3.8, w: 12, h: 1.5,
      fontSize: 16, fontFace: 'Microsoft YaHei',
      color: COLORS.textSecondary, lineSpacingMultiple: 1.5
    })
  }

  slide.addShape('rect' as any, {
    x: 0, y: 7.2, w: 13.33, h: 0.04,
    fill: { color: COLORS.border }
  })
}

function renderContentSlide(slide: PptxGenJS.Slide, title: string, markdown: string) {
  slide.addShape('rect' as any, {
    x: 0, y: 0, w: 13.33, h: 1.2,
    fill: { color: COLORS.bgCard }
  })

  slide.addText(title, {
    x: 0.5, y: 0.1, w: 12, h: 1,
    fontSize: 26, fontFace: 'Microsoft YaHei',
    color: COLORS.text, bold: true
  })

  const lines = markdown.split('\n')
    .filter(l => l.trim() && !l.match(/^#{1,3}\s/) && !l.startsWith('```') && !l.startsWith('|'))
    .map(l => l.replace(/^[-*]\s+/, '• ').replace(/[*_~`]/g, ''))
    .slice(0, 12)

  if (lines.length > 0) {
    slide.addText(lines.join('\n'), {
      x: 0.5, y: 1.5, w: 12, h: 5,
      fontSize: 16, fontFace: 'Microsoft YaHei',
      color: COLORS.text, lineSpacingMultiple: 1.6, valign: 'top'
    })
  }

  const mermaidBlocks = extractMermaidBlocks(markdown)
  if (mermaidBlocks.length > 0) {
    slide.addText('[Mermaid 图表 - 请查看在线预览]', {
      x: 0.5, y: 5.5, w: 12, h: 1,
      fontSize: 12, fontFace: 'Microsoft YaHei',
      color: COLORS.primary, italic: true
    })
  }
}

function renderCodeSlide(slide: PptxGenJS.Slide, title: string, markdown: string) {
  slide.addShape('rect' as any, {
    x: 0, y: 0, w: 13.33, h: 1.2,
    fill: { color: COLORS.bgCard }
  })

  slide.addText(title, {
    x: 0.5, y: 0.1, w: 12, h: 1,
    fontSize: 26, fontFace: 'Microsoft YaHei',
    color: COLORS.text, bold: true
  })

  const codeBlocks = extractCodeBlocks(markdown)
  if (codeBlocks.length > 0) {
    const block = codeBlocks[0]

    slide.addShape('roundRect' as any, {
      x: 0.4, y: 1.5, w: 12.5, h: 5.2,
      fill: { color: '1a1d2e' }, rectRadius: 0.1
    })

    slide.addText(block.language.toUpperCase(), {
      x: 0.6, y: 1.6, w: 1.5, h: 0.4,
      fontSize: 10, fontFace: 'Consolas',
      color: COLORS.accent, bold: true
    })

    slide.addText(block.code, {
      x: 0.6, y: 2.1, w: 12, h: 4.4,
      fontSize: 12, fontFace: 'Consolas',
      color: COLORS.text, lineSpacingMultiple: 1.4, valign: 'top'
    })
  }
}
