/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai/': RouteRecordInfo<
      '/ai/',
      '/ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai/generate': RouteRecordInfo<
      '/ai/generate',
      '/ai/generate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai/image': RouteRecordInfo<
      '/ai/image',
      '/ai/image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai/layout': RouteRecordInfo<
      '/ai/layout',
      '/ai/layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai/layout1': RouteRecordInfo<
      '/ai/layout1',
      '/ai/layout1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai/optimize': RouteRecordInfo<
      '/ai/optimize',
      '/ai/optimize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/material/': RouteRecordInfo<
      '/material/',
      '/material',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/material/icons': RouteRecordInfo<
      '/material/icons',
      '/material/icons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/material/images': RouteRecordInfo<
      '/material/images',
      '/material/images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/material/template': RouteRecordInfo<
      '/material/template',
      '/material/template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/ai/index.vue': {
      routes:
        | '/ai/'
      views:
        | never
    }
    'src/pages/ai/generate.vue': {
      routes:
        | '/ai/generate'
      views:
        | never
    }
    'src/pages/ai/image.vue': {
      routes:
        | '/ai/image'
      views:
        | never
    }
    'src/pages/ai/layout.vue': {
      routes:
        | '/ai/layout'
      views:
        | never
    }
    'src/pages/ai/layout1.vue': {
      routes:
        | '/ai/layout1'
      views:
        | never
    }
    'src/pages/ai/optimize.vue': {
      routes:
        | '/ai/optimize'
      views:
        | never
    }
    'src/pages/material/index.vue': {
      routes:
        | '/material/'
      views:
        | never
    }
    'src/pages/material/icons.vue': {
      routes:
        | '/material/icons'
      views:
        | never
    }
    'src/pages/material/images.vue': {
      routes:
        | '/material/images'
      views:
        | never
    }
    'src/pages/material/template.vue': {
      routes:
        | '/material/template'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
